name: Build entire repo

on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Initialize Submodule
        run: |
          git submodule update --init --recursive

      - name: Set up GCC for ARM
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install GCC for ARM
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Add STM32U5 Device Library to CMSIS
        run: |
          chmod +x tools/setup.sh
          sudo ./tools/setup.sh

      - name: Build STM32 Project
        run: |
          make blink 