name: Build blink example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Initialize Submodule
        run: |
          git submodule update --init --recursive

      - name: Set up GCC for ARM
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GCC for ARM
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Add STM32U5 Device Library to CMSIS
        run: |
          chmod +x setup.sh
          sudo ./setup.sh

      - name: Build STM32 Project
        working-directory: examples/blink
        run: |
          make all