name: Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CMSIS Submodule
        run: |
          git submodule update --init --recursive
      
      - name: Set up GCC for ARM
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install GCC for ARM
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Add STM32U5 Device Library to CMSIS
        run: |
          chmod +x tools/setup.sh
          sudo ./tools/setup.sh

      - name: Build BSP Library
        run: |
          make bsp

      # - name: Deploy to Staging
      #   run: |
      #     scp -r bsp/obj/* user@staging-server:/path/to/staging
      
      # - name: Deploy to Production
      #   if: github.event_name == 'push' && github.ref == 'refs/head/main'
      #   run: |
      #     scp -r bsp/obj/* user@production-server:/path/to/production