name: Doxygen

on:
  pull_request: 
    types:
      - closed
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxygen Documentation
        run: doxygen docs/Doxyfile

      - name: Archive Doxygen documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: ./docs/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Doxygen documentation
        uses: actions/download-artifact@v4
        with:
          name: doxygen-docs
          path: ./docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: doxygen-docs