name: Doxygen

on:
  push: 
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxygen Documentation
        run: doxygen docs/Doxyfile

      - name: Archive Doxygen documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: ./docs/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Doxygen documentation
        uses: actions/download-artifact@v4
        with:
          name: doxygen-docs
          path: ./docs/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/production'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html