name: Release

on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CMSIS Submodule
        run: |
          git submodule update --init --recursive
      
      - name: Set up GCC for ARM
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install GCC for ARM
        run: |
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Add STM32U5 Device Library to CMSIS
        run: |
          chmod +x tools/setup.sh
          sudo ./tools/setup.sh

      - name: Bump version and generate changelog
        run: |
          bumpversion --current-version $(git tag -l --sort=-committerdate | head -n 1 | sed 's/v//') patch
      
      - name: Tag the release
        run: git tag -a v${{ steps.version.outputs.new_version }} -m "Release v${{ steps.version.outputs.new_version }}"

      - name: Push tags
        run: git push origin --tags
